---
include:
  # korne
  - board: nice_nano_v2
    shield: korne_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: korne_dongle

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: common-config studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: korne_central_left

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=y
    artifact-name: korne_peripheral_left

  - board: nice_nano_v2
    shield: corne_right
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=n
    artifact-name: korne_peripheral_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: korne_reset_settings
