manifest:
  defaults:
    revision: v0.2
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: englmaxi
      url-base: https://github.com/englmaxi

    - name: tokyo2006
      url-base: https://github.com/tokyo2006

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    # modules
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

    - name: prospeśtor-zmk-module
      remote: tokyo2006
      revision: change_spi2
  self:
    path: config
